### PR TITLE
add opentopomap tiles url

### PR DESCRIPTION
**Pull request by wam23**
better map for VFR flights in the Alps

### CODE REVIEW

**Comment by foucdeg** [comment]
@wam23 Sorry I only just saw this :/
Thanks for your contribution.
Do you know if these map tiles are free to use?

**Comment by foucdeg** [comment]
@wam23 looks good to me :)

**Comment by wam23** [comment]
I'm not a lawyer, but should not be a problem: https://wiki.openstreetmap.org/wiki/OpenTopoMap#Usage
The tiles are also used by AviTab (https://github.com/fpw/avitab)

**Comment by foucdeg** [comment]
@wam23 available on https://public.airspaces.app and the desktop app upwards of version 2.6.0 :)

**Comment by wam23** [comment]
The app auto-updated one hour ago. I was really surprised to see OTM in the new version! Thank you

**Pull request merged**
